version: "3.8"

services:
  # MongoDB 数据库
  mongodb:
    image: mongo:6.0
    container_name: question-bank-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: yangchunrui2
      MONGO_INITDB_DATABASE: question-bank
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - question-bank-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # 后端服务器
  server:
    build:
      context: ../server
      dockerfile: Dockerfile
      args:
        BUILD_TIME: ${BUILD_TIME:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        VERSION: ${VERSION:-1.0.0}
    container_name: question-bank-server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:yangchunrui2@mongodb:27017/question-bank?authSource=admin
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      BUILD_TIME: ${BUILD_TIME:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
      VERSION: ${VERSION:-1.0.0}
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - question-bank-network

  # 前端客户端
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
      args:
        BUILD_TIME: ${BUILD_TIME:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        VERSION: ${VERSION:-1.0.0}
    container_name: question-bank-client
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000/api
      BUILD_TIME: ${BUILD_TIME:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
      VERSION: ${VERSION:-1.0.0}
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - question-bank-network

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: question-bank-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - client
      - server
    networks:
      - question-bank-network

volumes:
  mongodb_data:

networks:
  question-bank-network:
    driver: bridge
